[tool.poetry]
name = "parallel-parrot"
version = "0.0.1"
description = "A library for easily and efficiently using LLMs on tabular data"
authors = ["Brad Ito <phlogisticfugu@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.8.5"
pydantic = "^2.3.0"
aiohttp-retry = "^2.8.3"
uvloop = "^0.17.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.7.0"


[tool.poetry.group.extras.dependencies]
pandas = "*"

[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311']

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
